import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0/client";

export default function Home() {
  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;
  console.log(user ? true : false);
  console.log(user);

  if (user) {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.description}>
            <p>Welcome {user.name}!</p>
            <p>
              <a className={styles.main_link} href="/profile">
                Profile
              </a>
            </p>
            <p>
              <a className={styles.main_link} href="/api/auth/logout">
                Logout
              </a>
            </p>
          </div>
        </main>
      </div>
    );
  }
  return (
    <main className={styles.main}>
      <div className={styles.description}>
        <p>
          <a href="/api/auth/login">Login/Register</a>
        </p>
      </div>
    </main>
  );
}
